In [51]:
import numpy as np

In [52]:
arr = np.array([3, 5, 8])
arr

array([3, 5, 8])

In [53]:
arr = np.array([[3, 5, 8], [1, 4, 9]])
arr

array([[3, 5, 8],
       [1, 4, 9]])

In [54]:
arr.shape

(2, 3)

In [55]:
arr = np.random.rand(2, 3)
arr

array([[0.23298397, 0.63496437, 0.13592548],
       [0.4293709 , 0.96714335, 0.8493901 ]])

In [56]:
arr = np.array([1, 2, 3])
arr = arr * 5
arr

array([ 5, 10, 15])

In [57]:
arr1 = np.array([[1, 2, 3], [2, 3, 4]])
arr2 = np.array([[3, 4, 5], [4, 5, 6]])
arr = arr1 + arr2
arr

array([[ 4,  6,  8],
       [ 6,  8, 10]])

In [58]:
arr1 = np.array([[1, 2, 3],
                 [2, 3, 4]])

# 転置行列
arr2 = arr1.T
arr2

array([[1, 2],
       [2, 3],
       [3, 4]])

In [59]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])

# ベクトルの内積
np.dot(arr1, arr2)

20

In [60]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# 行列の積
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

In [61]:
# ランダム：引数：最小、最大、要素数
r = np.random.randint(0, 10, 10)
r

array([6, 7, 4, 6, 6, 6, 7, 2, 1, 5])

In [63]:
# 平均
m = np.mean(r)
m

5.0

In [65]:
# 標準偏差
s = np.std(r)
s

1.9493588689617927

In [67]:
# 集計（axis=0）
arr = np.array([[1, 2, 3],
                [2, 3, 4]])
np.sum(arr, axis = 0)

array([3, 5, 7])

In [69]:
# 集計（axis=1）
np.sum(arr, axis = 1)

array([6, 9])

In [71]:
# 2点間の距離（ベクトルの長さ）＝ユークリッド距離
a = np.array([2, 5])
b = np.array([7, 8])
np.linalg.norm(b - a)

5.830951894845301